backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
local_backend: true
media_folder: public/img
public_folder: img
media_library:
  name: uploadcare
  config:
    publicKey: 996f1aebccfeb885bab9
  settings:
    autoFilename: true # uploadcare crashes with not extension
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Paintings Page"
      name: "paintings"
      file: "content/paintings.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Paintings'
          name: "paintings"
          widget: list
          fields:
            - { label: "Publish Date", name: "date", widget: "datetime" }
            - { label: "Title", name: "title", widget: "string"}
            - { label: "Image", name: "image", widget: "image"}
            - { label: "Description", name: "description", widget: "markdown",required: false}
            - { label: "Size", name: "size", widget: "string",required: false}
            - { label: "Medium", name: "medium", widget: "string", required: false}
            - { label: "Price", name: "price", widget: "number", required: false}
            - label: "Categories"
              name: "categories"
              widget: "relation"
              collection: "relations"
              value_field: "categories.*.slug"
              display_fields: ["categories.*.title"]
              search_fields: ["categories.*.title","categories.*.slug"]
              multiple: true
              required: false
  - name: "relations"
    label: "Relations"
    files:
      - label: "Categories"
        name: "categories"
        file: "content/categories.md"
        fields:
          - label: 'Categories'
            name: "categories"
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string"}
              - { label: "Slug", name: "slug", widget: "string"}
