backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
local_backend: true
media_folder: public/img
public_folder: img
media_library:
  name: uploadcare
  config:
    publicKey: 996f1aebccfeb885bab9
  settings:
    autoFilename: true # uploadcare crashes with not extension
collections:
  - name: "paintings"
    label: "Paintings"
    label_singular: "Painting"
    folder: "content/paintings" 
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image",defaultOperations: "-/smart_resize/800x800/"}
      - { label: "Description", name: "description", widget: "markdown",required: false}
      - { label: "Size", name: "size", widget: "string",required: false}
      - { label: "Medium", name: "medium", widget: "string", required: false}
      - { label: "Price", name: "price", widget: "number", required: false}
      - label: "Categories"
        name: "categories"
        widget: "relation"
        collection: "relations"
        value_field: "allCategories.*.slug"
        display_fields: ["allCategories.*.title"]
        search_fields: ["allCategories.*.title","categories.*.slug"]
        multiple: true
        required: false
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "content/pages"
    create: true
    fields:
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown"}
  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Slug", name: "slug", widget: "string"}
